/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 0.13.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.okta.sdk.impl.resource.log;

import com.okta.sdk.impl.ds.InternalDataStore;
import com.okta.sdk.impl.resource.AbstractCollectionResource;
import com.okta.sdk.impl.resource.ArrayProperty;
import com.okta.sdk.impl.resource.Property;
import com.okta.sdk.resource.log.LogEvent;
import com.okta.sdk.resource.log.LogEventList;

import java.util.Map;

public class DefaultLogEventList extends AbstractCollectionResource<LogEvent> implements LogEventList {

    private static final ArrayProperty<LogEvent> ITEMS = new ArrayProperty<>("items", LogEvent.class);
    private static final Map<String, Property> PROPERTY_DESCRIPTORS = createPropertyDescriptorMap(ITEMS);

    public DefaultLogEventList(InternalDataStore dataStore) {
       super(dataStore);
    }

    public DefaultLogEventList(InternalDataStore dataStore, Map<String, Object> properties) {
       super(dataStore, properties);
    }

    public DefaultLogEventList(InternalDataStore dataStore, Map<String, Object> properties, Map<String, Object> queryParams) {
       super(dataStore, properties, queryParams);
    }

    @Override
    public Map<String, Property> getPropertyDescriptors() {
        return PROPERTY_DESCRIPTORS;
    }

    @Override
    protected Class<LogEvent> getItemType() {
        return LogEvent.class;
    }
}
