/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 0.13.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.okta.sdk.impl.resource.log;

import com.okta.sdk.impl.ds.InternalDataStore;
import com.okta.sdk.impl.resource.AbstractResource;
import com.okta.sdk.impl.resource.Property;
import com.okta.sdk.impl.resource.ResourceListProperty;
import com.okta.sdk.resource.log.LogIpAddress;
import com.okta.sdk.resource.log.LogRequest;

import java.util.List;
import java.util.Map;


/**
 * LogRequest
 */
@javax.annotation.Generated(
        value = "com.okta.swagger.codegen.OktaJavaClientImplCodegen",
        date  = "2018-02-11T21:21:50.835-05:00")
public class DefaultLogRequest extends AbstractResource implements LogRequest {

    private final static ResourceListProperty<LogIpAddress> ipChainProperty = new ResourceListProperty("ipChain", LogIpAddress.class);

    private final static Map<String, Property> PROPERTY_DESCRIPTORS = createPropertyDescriptorMap(ipChainProperty);

    public DefaultLogRequest(InternalDataStore dataStore) {
        super(dataStore);
    }

    public DefaultLogRequest(InternalDataStore dataStore, Map<String, Object> properties) {
        super(dataStore, properties);
    }

    @Override
    public Map<String, Property> getPropertyDescriptors() {
        return PROPERTY_DESCRIPTORS;
    }


    public List<LogIpAddress> getIpChain() {
        return (List<LogIpAddress>) getResourceListProperty(ipChainProperty);
    }

}
