/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 0.13.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.okta.sdk.impl.resource.log;

import com.okta.sdk.impl.ds.InternalDataStore;
import com.okta.sdk.impl.resource.AbstractResource;
import com.okta.sdk.impl.resource.Property;
import com.okta.sdk.impl.resource.StringProperty;
import com.okta.sdk.resource.log.LogIssuer;

import java.util.Map;


/**
 * LogIssuer
 */
@javax.annotation.Generated(
        value = "com.okta.swagger.codegen.OktaJavaClientImplCodegen",
        date  = "2018-02-11T21:21:50.835-05:00")
public class DefaultLogIssuer extends AbstractResource implements LogIssuer {

    private final static StringProperty idProperty = new StringProperty("id");
    private final static StringProperty typeProperty = new StringProperty("type");

    private final static Map<String, Property> PROPERTY_DESCRIPTORS = createPropertyDescriptorMap(idProperty, typeProperty);

    public DefaultLogIssuer(InternalDataStore dataStore) {
        super(dataStore);
    }

    public DefaultLogIssuer(InternalDataStore dataStore, Map<String, Object> properties) {
        super(dataStore, properties);
    }

    @Override
    public Map<String, Property> getPropertyDescriptors() {
        return PROPERTY_DESCRIPTORS;
    }


    public String getId() {
        return  getString(idProperty);
    }

    public String getType() {
        return  getString(typeProperty);
    }

}
