/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 0.13.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.okta.sdk.impl.resource.log;

import com.okta.sdk.impl.ds.InternalDataStore;
import com.okta.sdk.impl.resource.AbstractResource;
import com.okta.sdk.impl.resource.MapProperty;
import com.okta.sdk.impl.resource.Property;
import com.okta.sdk.impl.resource.StringProperty;
import com.okta.sdk.resource.log.LogTarget;

import java.util.Map;


/**
 * LogTarget
 */
@javax.annotation.Generated(
        value = "com.okta.swagger.codegen.OktaJavaClientImplCodegen",
        date  = "2018-02-11T21:21:50.835-05:00")
public class DefaultLogTarget extends AbstractResource implements LogTarget {

    private final static StringProperty alternateIdProperty = new StringProperty("alternateId");
    private final static MapProperty detailEntryProperty = new MapProperty("detailEntry");
    private final static StringProperty displayNameProperty = new StringProperty("displayName");
    private final static StringProperty idProperty = new StringProperty("id");
    private final static StringProperty typeProperty = new StringProperty("type");

    private final static Map<String, Property> PROPERTY_DESCRIPTORS = createPropertyDescriptorMap(alternateIdProperty, detailEntryProperty, displayNameProperty, idProperty, typeProperty);

    public DefaultLogTarget(InternalDataStore dataStore) {
        super(dataStore);
    }

    public DefaultLogTarget(InternalDataStore dataStore, Map<String, Object> properties) {
        super(dataStore, properties);
    }

    @Override
    public Map<String, Property> getPropertyDescriptors() {
        return PROPERTY_DESCRIPTORS;
    }


    public String getAlternateId() {
        return  getString(alternateIdProperty);
    }

    public Map<String, Object> getDetailEntry() {
        return  getMap(detailEntryProperty);
    }

    public String getDisplayName() {
        return  getString(displayNameProperty);
    }

    public String getId() {
        return  getString(idProperty);
    }

    public String getType() {
        return  getString(typeProperty);
    }

}
