/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 0.13.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.okta.sdk.impl.resource.log;

import com.okta.sdk.impl.ds.InternalDataStore;
import com.okta.sdk.impl.resource.AbstractResource;
import com.okta.sdk.impl.resource.Property;
import com.okta.sdk.impl.resource.StringProperty;
import com.okta.sdk.resource.log.LogOutcome;

import java.util.Map;


/**
 * LogOutcome
 */
@javax.annotation.Generated(
        value = "com.okta.swagger.codegen.OktaJavaClientImplCodegen",
        date  = "2018-02-11T21:21:50.835-05:00")
public class DefaultLogOutcome extends AbstractResource implements LogOutcome {

    private final static StringProperty reasonProperty = new StringProperty("reason");
    private final static StringProperty resultProperty = new StringProperty("result");

    private final static Map<String, Property> PROPERTY_DESCRIPTORS = createPropertyDescriptorMap(reasonProperty, resultProperty);

    public DefaultLogOutcome(InternalDataStore dataStore) {
        super(dataStore);
    }

    public DefaultLogOutcome(InternalDataStore dataStore, Map<String, Object> properties) {
        super(dataStore, properties);
    }

    @Override
    public Map<String, Property> getPropertyDescriptors() {
        return PROPERTY_DESCRIPTORS;
    }


    public String getReason() {
        return  getString(reasonProperty);
    }

    public String getResult() {
        return  getString(resultProperty);
    }

}
