/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 0.13.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.okta.sdk.resource.log;

import com.okta.sdk.resource.Resource;

import java.util.Date;
import java.util.List;


/**
 * LogEvent
 */
@javax.annotation.Generated(value = "com.okta.swagger.codegen.OktaJavaClientApiCodegen", date = "2018-02-11T21:21:35.941-05:00")
public interface LogEvent extends Resource {

    LogActor getActor();

    LogAuthenticationContext getAuthenticationContext();

    LogClient getClient();

    LogDebugContext getDebugContext();

    String getDisplayMessage();

    String getEventType();

    String getLegacyEventType();

    LogOutcome getOutcome();

    Date getPublished();

    LogRequest getRequest();

    LogSecurityContext getSecurityContext();

    LogSeverity getSeverity();

    List<LogTarget> getTarget();

    LogTransaction getTransaction();

    String getUuid();

    String getVersion();




}

