/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 0.13.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.okta.sdk.resource.log;

import com.okta.sdk.resource.Resource;

import java.util.Map;


/**
 * LogTarget
 */
@javax.annotation.Generated(value = "com.okta.swagger.codegen.OktaJavaClientApiCodegen", date = "2018-02-11T21:21:35.941-05:00")
public interface LogTarget extends Resource {

    String getAlternateId();

    Map<String, Object> getDetailEntry();

    String getDisplayName();

    String getId();

    String getType();




}

